default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: rogikhub_develop

test:
  <<: *default
  database: rogikhub_test
